CREATE TABLE IF NOT EXISTS "XApiUsage" (
  "id" TEXT NOT NULL,
  "monthStart" TIMESTAMP NOT NULL,
  "totalCostUsd" FLOAT NOT NULL DEFAULT 0,
  "tweetsFetched" INTEGER NOT NULL DEFAULT 0,
  "userLookups" INTEGER NOT NULL DEFAULT 0,
  "updatedAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "XApiUsage_pkey" PRIMARY KEY ("id")
);
