// BUILD 6 / F0 — surface publique. Observation seule : aucun score, aucun label,
// aucune lecture de coordination. Le module n'importe ni prisma ni réseau.
export {
  COORDINATED_EXIT_EXTRACT_VERSION,
  EXIT_EVENT_NATURE,
  OBSERVED_COUNTERPARTY_MEANING,
  type EvidenceProvenance,
  type ExitCandidateTx,
  type ExitEvent,
  type ExitEventNature,
  type ExitEventType,
  type ExitNativeTransfer,
  type ExitTokenBalanceChange,
  type ExitTokenTransfer,
} from "./types";
export {
  extractExitEvents,
  type ExitExclusionReason,
  type ExtractExitEventsInput,
  type ExtractExitEventsResult,
} from "./extract";
export {
  CO_EXIT_RULE_VERSION,
  MIN_SUBJECTS_IN_GROUP,
  MissingCoExitWindowError,
  observeCoExit,
  summarizeCoverage,
  type CoExitGroup,
  type CoExitObservation,
  type CoExitPair,
  type ExitCoverage,
  type ObserveCoExitInput,
  type PrimaryEvidenceCoverage,
  type SubjectCoverage,
  type TransactionCoverage,
} from "./coExit";
export {
  CATEGORY_MEANING,
  COORDINATED_EXIT_METHOD_REF,
  COORDINATED_EXIT_POLICY_VERSION,
  SELL_PROVENANCE_INVARIANT,
  SellProvenanceInvariantError,
  assertSellProvenanceInvariant,
  qualifyCoExit,
  type CoExitCategory,
  type CoExitCharacterisation,
  type MaterialityStatus,
  type QualifyCoExitInput,
} from "./qualify";
export {
  CO_EXIT_QUALIFICATION_TABLE,
  CoExitNatureRegistryMismatchError,
  EXIT_EVENT_TABLE,
  buildCoExitQualificationRow,
  buildExitEventRow,
  groupKeyOf,
  persistCoExit,
  satisfiesCoExitQualificationChecks,
  satisfiesExitEventChecks,
  type CoExitKeyConflict,
  type CoExitPersistReport,
  type CoExitQualificationRow,
  type CoExitStore,
  type ExitEventRow,
  type PersistCoExitInput,
  type StoredCoExitQualification,
  type StoredExitEvent,
} from "./persistence";
