export const ENV_KEYS = [
  "VAULT_AUDIT_SALT",
  "ADMIN_TOKEN",
  "EXPORT_MAX_ROWS",
  "ALLOW_ENTITY_EXPORT",
  "APPROVE_CHUNK_SIZE",
  "SCAN_RATE_LIMIT",
  "DATABASE_URL",
  "UPSTASH_REDIS_REST_URL",
] as const;
