import type { CanonicalIoc } from "./iocExportBuilder";
import type { VaultEvidenceSnapshot } from "@prisma/client";

// ── CSV utilities ─────────────────────────────────────────────────────────────

function escapeCsvField(value: string): string {
  if (
    value.includes(",") ||
    value.includes('"') ||
    value.includes("\n") ||
    value.includes("\r")
  ) {
    return `"${value.replace(/"/g, '""')}"`;
  }
  return value;
}

function row(fields: (string | null | undefined)[]): string {
  return fields
    .map((f) => escapeCsvField(f ?? ""))
    .join(",");
}

// ── A. CSV Full ───────────────────────────────────────────────────────────────

const CSV_FULL_HEADER = [
  "type",
  "value",
  "chain",
  "firstSeen",
  "lastSeen",
  "source",
  "confidence",
  "publishabilityStatus",
  "relatedCaseId",
  "relatedEntityId",
  "relatedEvidenceSnapshotId",
  "tags",
  "notes",
].join(",");

export function serializeCsvFull(iocs: CanonicalIoc[]): string {
  const rows = iocs.map((ioc) =>
    row([
      ioc.type,
      ioc.value,
      ioc.chain,
      ioc.firstSeen,
      ioc.lastSeen,
      ioc.source,
      ioc.confidence !== null ? String(ioc.confidence) : "",
      ioc.publishability,
      ioc.relatedCaseId,
      ioc.relatedEntityId,
      ioc.relatedEvidenceSnapshotId,
      ioc.tags.join(";"),
      ioc.notes,
    ])
  );
  return [CSV_FULL_HEADER, ...rows].join("\r\n");
}

// ── B. JSON Structured ────────────────────────────────────────────────────────

export type JsonExportMeta = {
  exportId: string;
  caseId: string;
  caseTitle: string;
  workspaceId: string;
  generatedAt: string;
  generatedBy: string;
  includedCounts: Record<string, number>;
  publishabilityFilter: string[];
  exportHashSha256: string;
  caseStatus: string;
  caseCreatedAt: string;
  caseUpdatedAt: string;
};

export function serializeJsonStructured(
  iocs: CanonicalIoc[],
  snapshots: VaultEvidenceSnapshot[],
  meta: JsonExportMeta,
  privateExcluded: number
): string {
  const snapshotMap = new Map(snapshots.map((s) => [s.id, s]));
  const snapshotSection = iocs
    .filter((i) => i.type === "EVIDENCE_SNAPSHOT" && i.relatedEvidenceSnapshotId)
    .map((i) => {
      const s = snapshotMap.get(i.relatedEvidenceSnapshotId!);
      return {
        id: i.relatedEvidenceSnapshotId,
        title: s?.title ?? i.value,
        sourceType: s?.sourceType ?? "OTHER",
        url: s?.url ?? null,
        publishability: i.publishability,
        snapshotRecordHashSha256: s?.contentHashSha256 ?? null,
        tags: i.tags,
        capturedAt: i.firstSeen,
        note: s?.note ?? null,
      };
    });

  const payload = {
    exportMeta: {
      caseId: meta.caseId,
      caseTitle: meta.caseTitle,
      workspaceId: meta.workspaceId,
      format: "JSON_STRUCTURED",
      generatedAt: meta.generatedAt,
      generatedBy: meta.generatedBy,
      includedCounts: meta.includedCounts,
      publishabilityFilter: meta.publishabilityFilter,
      exportHashSha256: meta.exportHashSha256,
    },
    caseSummary: {
      status: meta.caseStatus,
      createdAt: meta.caseCreatedAt,
      updatedAt: meta.caseUpdatedAt,
    },
    indicators: iocs.filter((i) => i.type !== "EVIDENCE_SNAPSHOT"),
    evidenceSnapshots: snapshotSection,
    excluded: {
      privateCount: privateExcluded,
    },
    legalNote:
      "Documented risk indicators. Not a legal determination. Not financial advice. " +
      "Source-attributed investigative material generated by INTERLIGENS.",
  };

  return JSON.stringify(payload, null, 2);
}

// ── C. STIX-like JSON ─────────────────────────────────────────────────────────

export function serializeStixLike(
  iocs: CanonicalIoc[],
  meta: Pick<JsonExportMeta, "exportId" | "caseId" | "generatedAt" | "exportHashSha256">
): string {
  const objects = iocs.map((ioc) => {
    const valueEscaped = ioc.value.replace(/'/g, "\\'");
    const pattern = `[${ioc.type.toLowerCase()}:value = '${valueEscaped}']`;
    return {
      type: "indicator",
      id: `indicator--${ioc.id}`,
      created: ioc.createdAt,
      modified: ioc.createdAt,
      name: `${ioc.type}: ${ioc.value.slice(0, 120)}`,
      pattern_type: "interligens",
      pattern,
      labels: ["source-attributed", "documented-risk-indicator"],
      confidence: ioc.confidence ?? 50,
      ...(ioc.chain ? { x_chain: ioc.chain } : {}),
      ...(ioc.tags.length > 0 ? { x_tags: ioc.tags } : {}),
      external_references: [
        {
          source_name: "interligens-case",
          external_id: ioc.relatedCaseId,
        },
      ],
    };
  });

  const bundle = {
    type: "bundle",
    spec_version: "interligens-stix-like-1.0",
    id: `bundle--${meta.exportId}`,
    created: meta.generatedAt,
    created_by_ref: "identity--interligens",
    objects,
    x_interligens_export: {
      caseId: meta.caseId,
      exportHashSha256: meta.exportHashSha256,
      disclaimer:
        "STIX-like format — not STIX 2.1 compliant. Documented risk indicators only. " +
        "Not a legal determination. Not financial advice.",
    },
  };

  return JSON.stringify(bundle, null, 2);
}

// ── E. Threat Intel CSV ───────────────────────────────────────────────────────

const THREAT_INTEL_HEADER = [
  "indicator_type",
  "indicator_value",
  "chain",
  "confidence",
  "first_seen",
  "last_seen",
  "source",
  "tags",
  "case_reference",
  "export_generated_at",
].join(",");

export function serializeThreatIntelCsv(
  iocs: CanonicalIoc[],
  caseId: string,
  generatedAt: string
): string {
  const rows = iocs.map((ioc) =>
    row([
      ioc.type,
      ioc.value,
      ioc.chain,
      ioc.confidence !== null ? String(ioc.confidence) : "",
      ioc.firstSeen,
      ioc.lastSeen,
      ioc.source,
      ioc.tags.join(";"),
      caseId,
      generatedAt,
    ])
  );
  return [THREAT_INTEL_HEADER, ...rows].join("\r\n");
}
