/**
 * src/lib/surveillance/evidencePack.ts
 *
 * Capture un post X → screenshot + HTML + manifest + SHA-256
 * Stocke sur R2, écrit en DB.
 */

import crypto from "crypto";
import { prisma } from "@/lib/prisma";
import { evidenceStorage } from "@/lib/storage/evidenceStorage";
import { CaptureStatus } from "@prisma/client";

const USER_AGENT =
  "Mozilla/5.0 (Windows NT 10.0; Win64; x64) " +
  "AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36";

// ─── HASHING ─────────────────────────────────────────────────────────────────

export function sha256(buffer: Buffer): string {
  return crypto.createHash("sha256").update(buffer).digest("hex");
}

export function sha256String(s: string): string {
  return sha256(Buffer.from(s, "utf-8"));
}

// ─── STORAGE KEY ─────────────────────────────────────────────────────────────

export function buildStorageKey(
  handle: string,
  capturedAt: Date,
  hashPrefix: string,
  filename: string
): string {
  const clean = handle.replace(/^@/, "").toLowerCase();
  const date = capturedAt.toISOString().slice(0, 10);
  const prefix = hashPrefix.slice(0, 8);
  return `evidence/${clean}/${date}/${prefix}/${filename}`;
}

// ─── MANIFEST ────────────────────────────────────────────────────────────────

export function buildManifest(input: {
  postUrl: string;
  handle: string;
  capturedAtUtc: Date;
  screenshotSha256: string;
  htmlSha256: string;
  textExcerpt: string;
}): string {
  return JSON.stringify({
    version: "1.0",
    tool: "interligens-evidence-pack",
    postUrl: input.postUrl,
    handle: input.handle,
    capturedAtUtc: input.capturedAtUtc.toISOString(),
    userAgent: USER_AGENT,
    artefacts: {
      screenshot: { filename: "screenshot.png", sha256: input.screenshotSha256, mimeType: "image/png" },
      html:       { filename: "page.html",      sha256: input.htmlSha256,       mimeType: "text/html" },
    },
    textExcerpt: input.textExcerpt,
    legalNote:
      "Generated by INTERLIGENS. Facts only — no accusations. " +
      "SHA-256 hashes computed at capture time.",
  }, null, 2);
}

// ─── PLAYWRIGHT CAPTURE ──────────────────────────────────────────────────────

async function capture(postUrl: string): Promise<{
  screenshotBuffer: Buffer;
  htmlBuffer: Buffer;
  textExcerpt: string;
  capturedAtUtc: Date;
}> {
  const { chromium } = await import("playwright");
  const browser = await chromium.launch({ headless: true });
  const ctx = await browser.newContext({
    userAgent: USER_AGENT,
    viewport: { width: 1280, height: 900 },
    locale: "en-US",
  });
  const page = await ctx.newPage();

  try {
    await page.goto(postUrl, { waitUntil: "networkidle", timeout: 30_000 });
    await page.waitForTimeout(3000);

    const html = await page.content();
    const title = await page.title();

    if (
      html.length < 2000 ||
      title.toLowerCase().includes("log in") ||
      title.toLowerCase().includes("sign in")
    ) {
      throw new Error("CAPTURE_BLOCKED");
    }

    const screenshot = await page.screenshot({ fullPage: false, type: "png" });
    const textExcerpt = await page.evaluate(() => {
      for (const sel of ['[data-testid="tweetText"]', "article", "main"]) {
        const el = document.querySelector(sel);
        if (el?.textContent?.trim()) return el.textContent.trim().slice(0, 500);
      }
      return document.body.innerText?.trim().slice(0, 500) ?? "";
    }).catch(() => "");

    return {
      screenshotBuffer: Buffer.from(screenshot),
      htmlBuffer: Buffer.from(html, "utf-8"),
      textExcerpt,
      capturedAtUtc: new Date(),
    };
  } finally {
    await browser.close();
  }
}

// ─── MAIN ────────────────────────────────────────────────────────────────────

export async function captureSocialPost(
  postUrl: string,
  handle: string,
  influencerId: string
) {
  const now = new Date();

  const post = await prisma.socialPost.create({
    data: { influencerId, postUrl, capturedAtUtc: now, captureStatus: CaptureStatus.PROCESSING },
  });

  try {
    const art = await capture(postUrl);
    const screenshotSha256 = sha256(art.screenshotBuffer);
    const htmlSha256 = sha256(art.htmlBuffer);
    const manifestContent = buildManifest({
      postUrl, handle,
      capturedAtUtc: art.capturedAtUtc,
      screenshotSha256, htmlSha256,
      textExcerpt: art.textExcerpt,
    });
    const manifestBuffer = Buffer.from(manifestContent, "utf-8");
    const manifestSha256 = sha256(manifestBuffer);

    const storageKeys = {
      screenshot: buildStorageKey(handle, art.capturedAtUtc, screenshotSha256, "screenshot.png"),
      html:       buildStorageKey(handle, art.capturedAtUtc, screenshotSha256, "page.html"),
      manifest:   buildStorageKey(handle, art.capturedAtUtc, screenshotSha256, "manifest.json"),
    };

    await Promise.all([
      evidenceStorage.put(storageKeys.screenshot, art.screenshotBuffer, "image/png"),
      evidenceStorage.put(storageKeys.html,       art.htmlBuffer,       "text/html"),
      evidenceStorage.put(storageKeys.manifest,   manifestBuffer,       "application/json"),
    ]);

    await prisma.socialPost.update({
      where: { id: post.id },
      data: {
        capturedAtUtc: art.capturedAtUtc,
        textExcerpt: art.textExcerpt || null,
        screenshotSha256, htmlSha256, manifestSha256,
        storageKeys,
        captureStatus: CaptureStatus.COMPLETED,
      },
    });

    return { socialPostId: post.id, status: CaptureStatus.COMPLETED, manifestSha256, storageKeys };

  } catch (err: any) {
    const isBlocked = err.message === "CAPTURE_BLOCKED";
    await prisma.socialPost.update({
      where: { id: post.id },
      data: {
        captureStatus: isBlocked ? CaptureStatus.BLOCKED : CaptureStatus.FAILED,
        errors: err.message,
      },
    });
    return {
      socialPostId: post.id,
      status: isBlocked ? CaptureStatus.BLOCKED : CaptureStatus.FAILED,
      error: err.message,
    };
  }
}

// ─── FALLBACK MANUEL ─────────────────────────────────────────────────────────

export async function captureManual(
  postUrl: string,
  handle: string,
  influencerId: string,
  pastedText: string,
  screenshotBuffer?: Buffer
) {
  const now = new Date();
  const textExcerpt = pastedText.slice(0, 500);
  const htmlBuffer = Buffer.from(`<pre>${pastedText}</pre>`, "utf-8");
  const htmlSha256 = sha256(htmlBuffer);
  const screenshotSha256 = screenshotBuffer ? sha256(screenshotBuffer) : "";

  const manifestContent = buildManifest({
    postUrl, handle, capturedAtUtc: now,
    screenshotSha256, htmlSha256, textExcerpt,
  });
  const manifestBuffer = Buffer.from(manifestContent, "utf-8");
  const manifestSha256 = sha256(manifestBuffer);

  const storageKeys: any = {
    html:     buildStorageKey(handle, now, htmlSha256, "page.html"),
    manifest: buildStorageKey(handle, now, htmlSha256, "manifest.json"),
  };
  if (screenshotBuffer) {
    storageKeys.screenshot = buildStorageKey(handle, now, screenshotSha256, "screenshot.png");
    await evidenceStorage.put(storageKeys.screenshot, screenshotBuffer, "image/png");
  }
  await Promise.all([
    evidenceStorage.put(storageKeys.html,     htmlBuffer,     "text/html"),
    evidenceStorage.put(storageKeys.manifest, manifestBuffer, "application/json"),
  ]);

  const post = await prisma.socialPost.create({
    data: {
      influencerId, postUrl, capturedAtUtc: now, textExcerpt,
      screenshotSha256: screenshotSha256 || null,
      htmlSha256, manifestSha256, storageKeys,
      captureStatus: CaptureStatus.COMPLETED,
    },
  });

  return { socialPostId: post.id, status: CaptureStatus.COMPLETED, manifestSha256, storageKeys };
}
